=== quotidian-ennui/fantastic-octo-parakeet/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="invoice" targetNamespace="invoice" elementFormDefault="qualified">
  <xs:element name="invoice">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="invnumber"/>
        <xs:element ref="invdate"/>
        <xs:element ref="customer"/>
        <xs:element ref="items"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="invnumber" type="xs:integer"/>
  <xs:element name="invdate" type="xs:date"/>
  <xs:element name="customer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="street"/>
        <xs:element ref="city"/>
        <xs:element ref="state"/>
        <xs:element ref="zip"/>
        <xs:element ref="phone"/>
        <xs:element ref="fax"/>
        <xs:element ref="attn"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="street" type="xs:string"/>
  <xs:element name="city" type="xs:string"/>
  <xs:element name="state" type="xs:string"/>
  <xs:element name="zip" type="xs:integer"/>
  <xs:element name="phone" type="xs:string"/>
  <xs:element name="fax">
    <xs:complexType/>
  </xs:element>
  <xs:element name="attn" type="xs:string"/>
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" maxOccurs="unbounded" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="date"/>
              <xs:element ref="description"/>
              <xs:element ref="quantity"/>
              <xs:element ref="unitprice"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="date" type="xs:date"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="quantity" type="xs:integer"/>
  <xs:element name="unitprice" type="xs:decimal"/>
</xs:schema>

=== quotidian-ennui/fantastic-octo-parakeet/invoice-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<invoice xmlns="invoice"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="invoice invoice.xsd">
    <invnumber>10001</invnumber>
    <invdate>2001-04-19</invdate>
    <customer>
    	<name>Coyote Group, LLC</name>
    	<street>3108 Suspendisse Ave</street>
    	<city>Berlin</city>
    	<state>New South Wales</state>
    	<zip>37337</zip>
    	<phone>1-987-649-5599</phone>
    	<fax></fax>
    	<attn>Wile E. Coyote</attn>
    </customer>
    <items>
        <item>
            <date>2001-04-01</date>
            <description>Anvil</description>
            <quantity>1</quantity>
            <unitprice>50.00</unitprice>
        </item>
        <item>
            <date>2001-04-04</date>
            <description>Stick of TNT</description>
            <quantity>6</quantity>
            <unitprice>10.00</unitprice>
        </item>
        <item>
            <date>2001-04-10</date>
            <description>Black Tunnel Spot</description>
            <quantity>3</quantity>
            <unitprice>99.00</unitprice>
        </item>
    </items>
</invoice>
